### ISSUE TITLE
关于 ansible  任务的疑问

### ISSUE THREAD

**Issue by billchen8888** [liyongjian5179/k8s-ansible#3]
我看到不少 task 里用了  connection: local
比如 https://github.com/liyongjian5179/k8s-ansible/blob/master/roles/master/tasks/genarate_kube_config.yml 

这是否意味着这里面的每一 task 都只是在主控机上运行完全相同的命令重复三遍（如果有 master 三台机器的话？）

比如：

- name: "Generate Token File"
  lineinfile:
    line: "{{ bootstrap_token }},kubelet-bootstrap,10001,\"system:kubelet-bootstrap\""
    path: "{{ cert_root_dir }}/token.csv"
    create: true
  when: token_csv is failed
  connection: local 

好像只是在主控机上三遍完全相同的动作（确保文件有那么一行），这个重复好像是不必要的。

**Comment by liyongjian5179** [comment]
首先，感谢您的关注哈
加了这个`connection: local` 只是意味着在主控机上生成这些文件，然后传给其他的机器，是在主控机上运行一次的, 像有一些其他的操作，比如: https://github.com/liyongjian5179/k8s-ansible/blob/master/roles/master/tasks/create_some_roles.yml 
```yaml
- name: "Add Kubelet-bootstrap RoleBinding For A CSR Is Automatically Created when a Kubelet is started "
  shell: |
    sleep 10
    kubectl  create  clusterrolebinding kubelet-bootstrap --clusterrole=system:node-bootstrapper --user=kubelet-bootstrap
  run_once: true
  ignore_errors: true
```
里面的 `run_once: true`是在三个 master 中选择一台执行这个 task
